// Mock data for UI development — replace with real Prisma queries in production

export const mockDashboardStats = {
  today: {
    date: new Date().toISOString(),
    totalBookings: 12,
    confirmedGuests: 67,
    revenue: 8940,
    guidesScheduled: 6,
    openSlots: 3,
    weatherStatus: "CLEAR",
    weatherTemp: 72,
    weatherWind: 8,
    operationalStatus: "OPEN",
  },
  week: {
    bookings: 74,
    revenue: 52340,
    guests: 398,
    avgRating: 4.8,
  },
  month: {
    bookings: 312,
    revenue: 218700,
    guests: 1680,
    avgOccupancy: 84,
  },
};

export const mockTodayBookings = [
  {
    id: "b1",
    confirmationNum: "SZL-001",
    status: "CONFIRMED",
    tourType: "ADVENTURE",
    timeSlot: "09:00",
    guestCount: 6,
    totalPrice: 780,
    guestName: "Johnson Family",
    source: "website",
  },
  {
    id: "b2",
    confirmationNum: "SZL-002",
    status: "CHECKED_IN",
    tourType: "CLASSIC",
    timeSlot: "09:00",
    guestCount: 4,
    totalPrice: 460,
    guestName: "Martinez Group",
    source: "phone",
  },
  {
    id: "b3",
    confirmationNum: "SZL-003",
    status: "IN_PROGRESS",
    tourType: "CLASSIC",
    timeSlot: "10:30",
    guestCount: 8,
    totalPrice: 920,
    guestName: "Smith Party",
    source: "website",
  },
  {
    id: "b4",
    confirmationNum: "SZL-004",
    status: "PENDING",
    tourType: "INTRO",
    timeSlot: "11:00",
    guestCount: 2,
    totalPrice: 180,
    guestName: "Williams, Sarah",
    source: "walk-in",
  },
  {
    id: "b5",
    confirmationNum: "SZL-005",
    status: "CONFIRMED",
    tourType: "CORPORATE",
    timeSlot: "13:00",
    guestCount: 20,
    totalPrice: 2800,
    guestName: "TechCorp Team Building",
    source: "partner",
  },
  {
    id: "b6",
    confirmationNum: "SZL-006",
    status: "CONFIRMED",
    tourType: "ADVENTURE",
    timeSlot: "14:30",
    guestCount: 5,
    totalPrice: 650,
    guestName: "Davis Group",
    source: "website",
  },
];

export const mockStaff = [
  {
    id: "s1",
    firstName: "Mike",
    lastName: "Torres",
    role: "HEAD_GUIDE",
    status: "ACTIVE",
    todayShift: "08:00 - 17:00",
    certifications: ["ACCT Level 3", "CPR/AED", "Wilderness First Responder"],
    certsExpiring: 0,
  },
  {
    id: "s2",
    firstName: "Sarah",
    lastName: "Chen",
    role: "SENIOR_GUIDE",
    status: "ACTIVE",
    todayShift: "08:00 - 17:00",
    certifications: ["ACCT Level 2", "CPR/AED", "First Aid"],
    certsExpiring: 1,
  },
  {
    id: "s3",
    firstName: "Jake",
    lastName: "Rivera",
    role: "GUIDE",
    status: "ACTIVE",
    todayShift: "09:00 - 18:00",
    certifications: ["ACCT Level 1", "CPR/AED"],
    certsExpiring: 0,
  },
  {
    id: "s4",
    firstName: "Emma",
    lastName: "Walsh",
    role: "GUIDE",
    status: "ACTIVE",
    todayShift: "09:00 - 18:00",
    certifications: ["ACCT Level 2", "CPR/AED", "First Aid"],
    certsExpiring: 0,
  },
  {
    id: "s5",
    firstName: "Carlos",
    lastName: "Mendez",
    role: "TRAINEE",
    status: "ACTIVE",
    todayShift: "10:00 - 16:00",
    certifications: ["CPR/AED"],
    certsExpiring: 0,
  },
  {
    id: "s6",
    firstName: "Lisa",
    lastName: "Park",
    role: "DISPATCH",
    status: "ACTIVE",
    todayShift: "08:00 - 17:00",
    certifications: ["CPR/AED"],
    certsExpiring: 0,
  },
];

export const mockEquipment = [
  {
    id: "e1",
    name: "Full-Body Harness #1",
    category: "HARNESS",
    serialNumber: "H-2021-001",
    status: "IN_SERVICE",
    lastInspection: "2026-02-28",
    nextInspection: "2026-03-07",
    manufacturer: "Petzl",
    model: "Corax",
  },
  {
    id: "e2",
    name: "Full-Body Harness #2",
    category: "HARNESS",
    serialNumber: "H-2021-002",
    status: "IN_SERVICE",
    lastInspection: "2026-02-28",
    nextInspection: "2026-03-07",
    manufacturer: "Petzl",
    model: "Corax",
  },
  {
    id: "e3",
    name: "Trolley System #4",
    category: "TROLLEY",
    serialNumber: "T-2020-004",
    status: "OUT_OF_SERVICE",
    lastInspection: "2026-02-25",
    nextInspection: null,
    manufacturer: "Head Rush Technologies",
    model: "Zipline Trolley Pro",
  },
  {
    id: "e4",
    name: "Helmet #12",
    category: "HELMET",
    serialNumber: "HLM-2022-012",
    status: "UNDER_INSPECTION",
    lastInspection: "2026-03-01",
    nextInspection: "2026-03-03",
    manufacturer: "Petzl",
    model: "Vertex",
  },
  {
    id: "e5",
    name: "Brake System — Line 3",
    category: "BRAKE_SYSTEM",
    serialNumber: "BS-2019-003",
    status: "IN_SERVICE",
    lastInspection: "2026-03-01",
    nextInspection: "2026-03-08",
    manufacturer: "Zip Stop",
    model: "ZS-100",
  },
];

export const mockIncidents = [
  {
    id: "i1",
    incidentNumber: "INC-2026-008",
    date: "2026-02-28",
    type: "NEAR_MISS",
    severity: "LOW",
    location: "Platform 3",
    description: "Guest's helmet clip partially undone prior to departure — caught by guide during final check.",
    status: "CLOSED",
    reportedBy: "Mike Torres",
  },
  {
    id: "i2",
    incidentNumber: "INC-2026-007",
    date: "2026-02-20",
    type: "EQUIPMENT_FAILURE",
    severity: "MEDIUM",
    location: "Line 4",
    description: "Trolley #4 showed unusual friction; tour halted. Equipment pulled from service pending inspection.",
    status: "UNDER_REVIEW",
    reportedBy: "Sarah Chen",
  },
  {
    id: "i3",
    incidentNumber: "INC-2026-006",
    date: "2026-02-14",
    type: "GUEST_INJURY",
    severity: "LOW",
    location: "Landing Platform 2",
    description: "Guest scraped palm on landing. Minor abrasion treated with first aid on site.",
    status: "CLOSED",
    reportedBy: "Jake Rivera",
  },
];

export const mockRevenueData = [
  { month: "Sep", revenue: 142000, bookings: 218, guests: 1180 },
  { month: "Oct", revenue: 128500, bookings: 197, guests: 1064 },
  { month: "Nov", revenue: 86200, bookings: 132, guests: 712 },
  { month: "Dec", revenue: 67400, bookings: 103, guests: 556 },
  { month: "Jan", revenue: 54800, bookings: 84, guests: 453 },
  { month: "Feb", revenue: 98600, bookings: 151, guests: 815 },
  { month: "Mar (MTD)", revenue: 38200, bookings: 58, guests: 313 },
];

export const mockTourMix = [
  { name: "Classic Tour", value: 38, color: "#0ea5e9" },
  { name: "Full Adventure", value: 28, color: "#22c55e" },
  { name: "Intro", value: 15, color: "#f59e0b" },
  { name: "Corporate", value: 11, color: "#8b5cf6" },
  { name: "Private", value: 5, color: "#ec4899" },
  { name: "Night Ride", value: 3, color: "#6366f1" },
];

export const mockWeeklyOccupancy = [
  { day: "Mon", occupancy: 72 },
  { day: "Tue", occupancy: 68 },
  { day: "Wed", occupancy: 81 },
  { day: "Thu", occupancy: 75 },
  { day: "Fri", occupancy: 94 },
  { day: "Sat", occupancy: 100 },
  { day: "Sun", occupancy: 98 },
];
